In [1]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import  pandas as pd

## load the dataset
data = gutenberg.raw('carroll-alice.txt')
## save to a file
with open('alice.txt','w') as file:
    file.write(data)
# Print the first few characters to verify
print(data[:500])

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\Uyama\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


[Alice's Adventures in Wonderland by Lewis Carroll 1865]

CHAPTER I. Down the Rabbit-Hole

Alice was beginning to get very tired of sitting by her sister on the
bank, and of having nothing to do: once or twice she had peeped into the
book her sister was reading, but it had no pictures or conversations in
it, 'and what is the use of a book,' thought Alice 'without pictures or
conversation?'

So she was considering in her own mind (as well as she could, for the
hot day made her feel very sleepy an


In [2]:
## Data Preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

##load the dataset
with open('alice.txt','r') as file:
    text=file.read().lower()

## Tokenize the text-creating indexes for words
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words

2858

In [3]:
tokenizer.word_index

{'the': 1,
 "'": 2,
 'and': 3,
 'to': 4,
 'a': 5,
 'she': 6,
 'of': 7,
 'it': 8,
 'said': 9,
 'alice': 10,
 'in': 11,
 'was': 12,
 'you': 13,
 'i': 14,
 'that': 15,
 'as': 16,
 'her': 17,
 'at': 18,
 'on': 19,
 'with': 20,
 'all': 21,
 'had': 22,
 'be': 23,
 'for': 24,
 'so': 25,
 'very': 26,
 'not': 27,
 'but': 28,
 'this': 29,
 'little': 30,
 "'i": 31,
 'they': 32,
 'out': 33,
 'he': 34,
 'is': 35,
 'down': 36,
 'what': 37,
 'up': 38,
 'one': 39,
 'his': 40,
 'about': 41,
 'them': 42,
 'know': 43,
 'like': 44,
 'were': 45,
 'went': 46,
 'again': 47,
 'herself': 48,
 'then': 49,
 'would': 50,
 'no': 51,
 'could': 52,
 'have': 53,
 'if': 54,
 'thought': 55,
 'when': 56,
 'do': 57,
 'or': 58,
 'there': 59,
 'time': 60,
 'queen': 61,
 'into': 62,
 'see': 63,
 'me': 64,
 'off': 65,
 'king': 66,
 'did': 67,
 'your': 68,
 'by': 69,
 'began': 70,
 'its': 71,
 'turtle': 72,
 "'and": 73,
 'way': 74,
 'an': 75,
 'my': 76,
 'mock': 77,
 'quite': 78,
 'who': 79,
 "don't": 80,
 'hatter': 81,
 'gry

In [3]:
## create inoput sequences
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence) 

In [4]:
input_sequences

[[315, 490],
 [315, 490, 11],
 [315, 490, 11, 886],
 [315, 490, 11, 886, 69],
 [315, 490, 11, 886, 69, 1585],
 [315, 490, 11, 886, 69, 1585, 1586],
 [315, 490, 11, 886, 69, 1585, 1586, 1587],
 [316, 14],
 [316, 14, 36],
 [316, 14, 36, 1],
 [316, 14, 36, 1, 99],
 [316, 14, 36, 1, 99, 628],
 [10, 12],
 [10, 12, 268],
 [10, 12, 268, 4],
 [10, 12, 268, 4, 105],
 [10, 12, 268, 4, 105, 26],
 [10, 12, 268, 4, 105, 26, 491],
 [10, 12, 268, 4, 105, 26, 491, 7],
 [10, 12, 268, 4, 105, 26, 491, 7, 368],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69, 17],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69, 17, 441],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69, 17, 441, 19],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69, 17, 441, 19, 1],
 [887, 3],
 [887, 3, 7],
 [887, 3, 7, 369],
 [887, 3, 7, 369, 145],
 [887, 3, 7, 369, 145, 4],
 [887, 3, 7, 369, 145, 4, 57],
 [887, 3, 7, 369, 145, 4, 57, 137],
 [887, 3, 7, 369, 145, 4, 57, 137, 58],
 [887, 3, 7, 369, 145, 4, 57, 137

In [7]:
## Pad Sequences
max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

18

In [8]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,  315,  490],
       [   0,    0,    0, ...,  315,  490,   11],
       [   0,    0,    0, ...,  490,   11,  886],
       ...,
       [   0,    0,    0, ...,    3,    1, 2857],
       [   0,    0,    0, ...,    1, 2857, 1563],
       [   0,    0,    0, ..., 2857, 1563,  846]])

In [9]:
##create predicitors and label
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]

In [10]:
x

array([[   0,    0,    0, ...,    0,    0,  315],
       [   0,    0,    0, ...,    0,  315,  490],
       [   0,    0,    0, ...,  315,  490,   11],
       ...,
       [   0,    0,    0, ...,  328,    3,    1],
       [   0,    0,    0, ...,    3,    1, 2857],
       [   0,    0,    0, ...,    1, 2857, 1563]])

In [11]:
y

array([ 490,   11,  886, ..., 2857, 1563,  846])

In [12]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [13]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [17]:
# Define early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

In [15]:
## Train our LSTM RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU

## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 17, 100)           285800    
                                                                 
 lstm (LSTM)                 (None, 17, 150)           150600    
                                                                 
 dropout (Dropout)           (None, 17, 150)           0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               100400    
                                                                 
 dense (Dense)               (None, 2858)              288658    
                                                                 
Total params: 825458 (3.15 MB)
Trainable params: 825458 (3.15 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
## Train the model
history=model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1,callbacks=[early_stopping])


Epoch 1/50
634/634 [==============================] - 31s 49ms/step - loss: 4.4712 - accuracy: 0.1786 - val_loss: 5.7189 - val_accuracy: 0.1502
Epoch 2/50
634/634 [==============================] - 38s 60ms/step - loss: 4.3278 - accuracy: 0.1853 - val_loss: 5.7277 - val_accuracy: 0.1522
Epoch 3/50
634/634 [==============================] - 39s 62ms/step - loss: 4.2068 - accuracy: 0.1923 - val_loss: 5.7644 - val_accuracy: 0.1541
Epoch 4/50
634/634 [==============================] - 41s 65ms/step - loss: 4.0881 - accuracy: 0.2038 - val_loss: 5.8002 - val_accuracy: 0.1549
Epoch 5/50
634/634 [==============================] - 43s 68ms/step - loss: 3.9685 - accuracy: 0.2109 - val_loss: 5.8554 - val_accuracy: 0.1514
Epoch 6/50
634/634 [==============================] - 58s 92ms/step - loss: 3.8521 - accuracy: 0.2175 - val_loss: 5.8816 - val_accuracy: 0.1591
Epoch 7/50
634/634 [==============================] - 42s 67ms/step - loss: 3.7443 - accuracy: 0.2271 - val_loss: 5.9317 - val_accuracy:

In [21]:
# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [23]:
input_text="Alice was beginning to get very tired"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word Prediction:{next_word}")

Input text:Alice was beginning to get very tired
Next Word Prediction:of


In [24]:
## Save the model
model.save("next_word_alice_lstm.h5")
## Save the tokenizer
import pickle
with open('tokenizer_slice.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

c:\Users\Uyama\Downloads\JANE-UDEMY\NLP\Deep-Learning-NLP\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [29]:
input_text="heap of sticks and dry leaves,"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word Prediction:{next_word}")

Input text:heap of sticks and dry leaves,
Next Word Prediction:and


In [31]:
input_text="she came upon a"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word Prediction:{next_word}")

Input text:she came upon a
Next Word Prediction:little
